config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root to: "welcome#index"
  get 'users/my_portfolio', to: 'users#my_portfolio', as: "my_portfolio"
  get 'users/friends', to: 'users#friends', as: "friends"
  get 'search_stock', to: 'stocks#search'
  get 'search_friend', to: 'users#search'

  resources :user_stocks, only: [:create, :destroy]
  resources :friendships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: "User" 
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_lookup(ticker_symbol)
    ticker_symbol.upcase

    client = IEX::Api::Client.new(
      publishable_token: Rails.application.credentials.iex_client[:sandbox_api_key],
      endpoint: 'https://sandbox.iexapis.com/v1'
    )

    # The following is an exception to handle invalid ticker searches (other than empty). Basically, if it doesn't find the symbol, it will return nil and then it will render the portfolio form again. It's similar to a conditional in a way.
    begin
      new(name: client.company(ticker_symbol).company_name , ticker: ticker_symbol, last_price: client.price(ticker_symbol))
    rescue => exception
      return nil
    end
  end
  
  def self.check_db(ticker_symbol)
    where(ticker: ticker_symbol).first
  end
end

app/models/user.rb
require 'rubygems'
require 'zapier_ruby'

class User < ApplicationRecord
  after_create :zap_new_user

  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Following method checks if the user stock count is less than ten, we will use it to determine if he can add more stocks to the portfolio and also to display the proper message in case this is true.
  def tracking_limit_exceeded?
    stocks.count < 10
  end

  def already_tracking?(ticker_symbol)
    # First we check if the stock already exists in our table, if it doesn't it means that the user is not tracking it for sure. Notice that we are using our Stock.check_db instance method to check in the DB (calling and reusing method):
    stock = Stock.check_db(ticker_symbol)
    # Next condition allows the method to carry on in case there is no stock object with said ticker_symbol:
    return false unless stock
    # If we reach this point, it means that the stock exists in the DB, however, we still need to check if the current user is tracking it:
    stocks.where(id: stock.id).exists?
  end

  # Finally, this method calls both of our previous methods to determine if the stock can be added to our tracked stocks portfolio
  def can_track_stock?(ticker_symbol)
    tracking_limit_exceeded? && !already_tracking?(ticker_symbol)
  end

  def full_name
    return "#{first_name} #{last_name}" if first_name || last_name
    "Anonymous Mofo"
  end

  # Following methods query the db to look for matches on first_name, last_name or email

  def self.search(param)
    # first we strip whatever is passed to eliminate extra spaces
    param.strip!
    # Next store the concatenated methods in a variable. Notice that we called the #uniq method on it to make sure that the value is not repeated when performing the query
    to_send_back = (first_name_match(param) + last_name_match(param) + email_match(param)).uniq
    return nil unless to_send_back
    to_send_back
    # raise
  end

  def self.first_name_match(param)
    matches('first_name', param)
  end
  
  def self.last_name_match(param)
    matches('last_name', param)
  end

  def self.email_match(param)
    matches('email', param)
  end

  def self.matches(field_name, param)
    # When defining class level methods, we can omit the class name (User in this case)
    where("#{field_name} like ?", "%#{param}%")
  end

  def not_friends_with?(friend_id)
    !self.friends.where(id: friend_id).exists?
  end

  def zap_new_user
    ZapierRuby.configure do |c|
     c.web_hooks = {user_zap: "b9yz5m5"}
     c.enable_logging = false
     c.account_id = "11614338"
    end
    
    zapper = ZapierRuby::Zapper.new(:user_zap)
    
    if zapper.zap({
      nickname: self.full_name, 
      email: self.email
      })
      puts "zapped it"
    else
      puts "it remains unzapped"
    end
  end
  
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def create
    @friendship = Friendship.create(user_id: current_user.id, friend_id: params[:friend])
    # @friendship.user = current_user
    # @friendship.friend = User.find(params[:friend])
    
    # friend = User.find(params[:friend])
    # current_user.friendships.build(friend_id: friend.id)
    # byebug
    redirect_to friends_path
  end
  

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy

    redirect_to friends_path
  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_lookup(params[:stock])
      if @stock
        # The following method accepts a block and expects a js.erb partial
        respond_to do |format|
          format.js { render partial: 'users/stocks' }
        end
      else
        respond_to do |format|
          flash.now[:alert] =  "Please enter a valid Symbol"
          format.js { render partial: 'users/stocks' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] =  "Please enter a Symbol"
        format.js { render partial: 'users/stocks' }
      end
    end
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController
  
  def create
    stock = Stock.check_db(params[:ticker])
    if stock.blank?
      stock = Stock.new_lookup(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user,  stock: stock)
    flash[:notice] = "Stock #{stock.name} was succesfully added to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id ).first
    user_stock.destroy
    flash[:notice] = "#{stock.name} was succesfully removed from portfolio"

    redirect_to my_portfolio_path
  end

end

# else
#   flash[:alert] = "Stock was not added, please try again"
#   render "my_portfolio"

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @tracked_stocks = current_user.stocks
  end

  def friends
    @friends = current_user.friends
  end 

  def search
    # @friend = User.where(email: params[:friend]).first
    # byebug
    # render json: @friend
    if params[:friend].present?
      @friends = User.search(params[:friend])
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friends' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid email"
          format.js { render partial: 'users/friends'}
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter an email"
        format.js { render partial: 'users/friends' }
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%# Crips IM script %>
    <script type="text/javascript">
      window.$crisp=[];window.CRISP_WEBSITE_ID="e93e073a-1f69-4cbc-8934-f9e1611e65bb";
      (function(){d=document;s=d.createElement("script");s.src="https://client.crisp.chat/l.js";s.async=1;d.getElementsByTagName("head")[0].appendChild(s);})();
      window.$crisp.push(["set", "message:text", ["Hi! I'd like to get help right now."]])
    </script>

  </head>


  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= render 'shared/messages' %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_friend.html.erb
<div class="stock-block">
  <%= render 'shared/messages' %>
</div>

<% if @friends %>
  <div class="card card-header stock-block main-stock-block">
      <table>
    <% @friends.each do |friend| %>
    <tbody>
      <% if friend != current_user %>
        <tr>
          <td class="mr-2">
            <span>Name: </span><%= friend.full_name %>
          </td>
          <td class="mr-2">
            <span> Email: </span><%= friend.email %>
          </td>
          <td class="mr-2">
            <span> Actions: </span>
          </td>
          <td class="mr-2">
            <%= link_to 'Visit Profile', '#', class: 'btn btn-xs  btn-success ml-2' %>
          </td>
            <td class="mr-2">
          <% if current_user.not_friends_with?(friend.id) %>
              <%= link_to 'Follow friend', friendships_path(friend: friend), class: 'btn btn-xs btn-success ml-2', method: :post %>
          <% else %>
            <span class="badge badge-secondary">You are friends already</span>
          <% end %>
            </td>
        </tr>
      <% end %>
    </tbody>
    <% end %>
      </table>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>

<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to "Finance Tracker", root_path, class: "navbar-brand" %>
    <% if user_signed_in? %>
      <button class="navbar-toggler" type="button"    aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Profile
        </a>
          <div class="dropdown-menu drop-box" aria-labelledby="navbarDropdown">
            <%= link_to edit_user_registration_path, class:'nav-link dropdown-item' do %>
              <%= fa_icon 'edit' %> Edit profile
            <% end %>
          </div>
        </li>
        <li class="nav-item <% 'active' if request.path == my_portfolio_path  %>">
            <%= link_to 'My Portfolio', my_portfolio_path, class:'nav-link' %>
        </li>
        <li class="nav-item <% 'active' if request.path == friends_path  %>">
            <%= link_to 'Friends', friends_path, class:'nav-link' %>
        </li>
        </ul>
      </div>
    <% end %>
    
      <div class="ml-auto row">
        <% if user_signed_in? %>
        <ul class="navbar-nav">
          <li class="nav-item user-name">
            <%= fa_icon 'user', class: "mr-1" %> 
            <% unless current_user.first_name.nil? || current_user.last_name.nil? %>
              <%= current_user.full_name %>
            <% end %>
          </li>
        </ul>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %>
        <% else %>
          <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-primary mr-sm-2" %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary" %>
        <% end %>
      </div>
  </div>
</nav>

app/views/shared/_stock.html.erb
<div class="stock-block">
  <%= render 'shared/messages' %>
</div>

<% if @stock %>
  <div class="card card-header stock-block main-stock-block">
    <span>Symbol:</span> <%= @stock.ticker %>
    <span>Name:</span> <%= @stock.name %>
    <span>Last Price:</span> <%= @stock.last_price %>
    <%# Following link_to adds a stock to the user's portfolio. It requires the create route and the method which in this case is post given that we are sending info to the DB. Note that the route requires two arguments that will be passed (user_id and ticker). The ticker will help us check if the stock already exists and if not, we can create it%>
    <% if current_user.can_track_stock?(@stock.ticker) %>
      <%= link_to "ADD TO PORTFOLIO", user_stocks_path( user: current_user, ticker: @stock.ticker), class: "btn btn-xs btn-success ml-2", method: :post %>
    <% else %>
      <span class="badge badge-warning ml-1">
        You are already tracking
        <% if !current_user.tracking_limit_exceeded? %>
          10 stocks
        <% end %> 
        <% if current_user.already_tracking?(@stock.ticker)%>
          this stock
        <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/user_friends/_list.html.erb
<div class="row">
  <div class="col-8">
    <table class="table table-hover table-dark">
      <thead>
        <tr>
          <th scope="col">Email</th>
          <th scope="col">Name</th>
          <th scope="col">Last Name</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @friends.each do |friend| %>
          <tr>
            <th scope="row"><%= friend.email %></th>
            <td><%= friend.first_name %></td>
            <td><%= friend.last_name  %></td>
            <%# <td><%= 'Placeholder Actions' %>
            <td><%= link_to "Stop Following", friendship_path(friend.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-warning" %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/user_stocks/_list.html.erb
<div class="row">
  <div class="col-8">
    <table class="table table-hover table-dark">
      <thead>
        <tr>
          <th scope="col">Ticker</th>
          <th scope="col">Name</th>
          <th scope="col">Price</th>
          <th scope="col">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @tracked_stocks.each do |stock| %>
          <tr>
            <th scope="row"><%= stock.ticker.upcase %></th>
            <td><%= stock.name %></td>
            <td><%= stock.last_price  %></td>
            <td><%= 'Placeholder Actions' %></td>
            <td><%= link_to "Remove", user_stock_path(stock), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-warning" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/users/_friends.js.erb
document.querySelector('.friends').innerHTML = '<%= j render 'shared/friend.html' %>'

app/views/users/_stocks.js.erb
document.querySelector('.stocks').innerHTML = '<%= j render 'shared/stock.html'  %>'

<%# alert("Hello world") %>

app/views/users/friends.html.erb
<h1>My Friend$</h1>
<p>Friends are like money, always there when you need them!</p>

<div class="search-form">
  <h3>Find your friends</h3>
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-6 no-right-padding">
        <%= text_field_tag :friend, params[:friend], placeholder:"User email", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="friends">
  
</div>
<%# Following lines display the friends list only if the user has friends %>
<% if !@friends.empty? %>
  <%= render 'user_friends/list' %>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>Stock Portfolio</h1>
<p>Make money money money, make money money money...</p>

<div class="search-form">
  <h3>Search stocks</h3>
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="form-group row">
      <div class="col-6 no-right-padding">
        <%= text_field_tag :stock, params[:stock], placeholder:"Ticker Symbol", autofocus: true, class: "form-control form-control-lg" %>
      </div>
      <div class="col-3 no-left-padding">
        <%= button_tag type: :submit, class: "btn btn-success" do %>
          <%= fa_icon 'search 2x' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div class="stocks">

</div>
<% if !@tracked_stocks.empty? %>
  <%= render 'user_stocks/list' %>
<% end %>

app/views/welcome/index.html.erb
<h1>Welcomet to the Finance Tracker</h1>

<%= link_to "Sign out", destroy_user_session_path, method: :delete %>